In [ ]:
!kaggle datasets download -d thoughtvector/customer-support-on-twitter

Downloading customer-support-on-twitter.zip to /content
100% 169M/169M [00:00<00:00, 265MB/s]
100% 169M/169M [00:00<00:00, 271MB/s]

In [ ]:
!unzip /content/customer-support-on-twitter.zip

Archive:  /content/customer-support-on-twitter.zip
  inflating: sample.csv
  inflating: twcs/twcs.csv

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#NTLK, Spacy

In [ ]:
df=pd.read_csv('/content/sample.csv')

In [ ]:
df

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,119237,105834,True,Wed Oct 11 06:55:44 +0000 2017,@AppleSupport causing the reply to be disregar...,119236,NaN
1,119238,ChaseSupport,False,Wed Oct 11 13:25:49 +0000 2017,@105835 Your business means a lot to us. Pleas...,NaN,119239.0
2,119239,105835,True,Wed Oct 11 13:00:09 +0000 2017,@76328 I really hope you all change but I'm su...,119238,NaN
3,119240,VirginTrains,False,Tue Oct 10 15:16:08 +0000 2017,@105836 LiveChat is online at the moment - htt...,119241,119242.0
4,119241,105836,True,Tue Oct 10 15:17:21 +0000 2017,@VirginTrains see attached error message. I've...,119243,119240.0
...,...,...,...,...,...,...,...
88,119330,105859,True,Wed Oct 11 13:50:42 +0000 2017,@105860 I wish Amazon had an option of where I...,119329,119331.0
89,119331,105860,True,Wed Oct 11 13:47:14 +0000 2017,They reschedule my shit for tomorrow https://t...,119330,NaN
90,119332,Tesco,False,Wed Oct 11 13:34:06 +0000 2017,"@105861 Hey Sara, sorry to hear of the issues ...",119333,119334.0
91,119333,105861,True,Wed Oct 11 14:05:18 +0000 2017,@Tesco bit of both - finding the layout cumber...,"119335,119336",119332.0
92,119335,Tesco,False,Wed Oct 11 15:38:07 +0000 2017,@105861 If that doesn't help please DM your fu...,NaN,119333.0

In [ ]:
tweet_data = df[['tweet_id', 'text']]

In [ ]:
print(tweet_data.head())

   tweet_id                                               text
0    119237  @AppleSupport causing the reply to be disregar...
1    119238  @105835 Your business means a lot to us. Pleas...
2    119239  @76328 I really hope you all change but I'm su...
3    119240  @105836 LiveChat is online at the moment - htt...
4    119241  @VirginTrains see attached error message. I've...

In [3]:

df = pd.read_csv(file_path)

df['text'] = df['text'].str.lower()

print(df.head())

NameError: name 'file_path' is not defined

In [ ]:
df = pd.read_csv("customer_support_twitter.csv")
def remove_punctuation(text):
      text_no_punctuation = re.sub(r'[^\w\s]', '', text)
    return text_no_punctuation

df['text'] = df['text'].apply(remove_punctuation)
print(df.head())

In [ ]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt')

df = pd.read_csv("customer_support_twitter.csv")
stop_words = set(stopwords.words('english'))
def remove_stopwords(text):
    words = word_tokenize(text)
    filtered_words = [word for word in words if word.lower() not in stop_words]
    text_without_stopwords = ' '.join(filtered_words)
    return text_without_stopwords
df['text'] = df['text'].apply(remove_stopwords)
print(df.head())

In [ ]:
import pandas as pd
from collections import Counter

df = pd.read_csv("customer_support_twitter.csv")
all_text = ' '.join(df['text'])
words = all_text.split()
word_freq = Counter(words)

num_freq_words_to_remove = 10
most_common_words = word_freq.most_common(num_freq_words_to_remove)

most_common_words = [word for word, freq in most_common_words]

def remove_common_words(text):
    words = text.split()
    filtered_words = [word for word in words if word not in most_common_words]
    text_without_common_words = ' '.join(filtered_words)
    return text_without_common_words
df['text'] = df['text'].apply(remove_common_words)
print(df.head())

In [ ]:
import pandas as pd
from collections import Counter

df = pd.read_csv("customer_support_twitter.csv")

all_text = ' '.join(df['text'])

words = all_text.split()

word_freq = Counter(words)

min_word_freq = 2

rare_words = [word for word, freq in word_freq.items() if freq < min_word_freq]
def remove_rare_words(text):
    words = text.split()
    filtered_words = [word for word in words if word not in rare_words]
    text_without_rare_words = ' '.join(filtered_words)
    return text_without_rare_words

df['text'] = df['text'].apply(remove_rare_words)

print(df.head())

In [ ]:
import pandas as pd
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('wordnet')
df = pd.read_csv("customer_support_twitter.csv")

lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    tokens = word_tokenize(text)
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in tokens]
    lemmatized_text = ' '.join(lemmatized_tokens)
    return lemmatized_text

df['text'] = df['text'].apply(lemmatize_text)

print(df.head())

In [4]:
import pandas as pd
import re

+df = pd.read_csv("customer_support_twitter.csv")
def remove_special_characters(text):
    text = re.sub(r'\p{Emoji}', '', text)
    text = re.sub(r'[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251]+', '', text)
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'<[^>]+>', '', text)
    return text

df['text'] = df['text'].apply(remove_special_characters)
print(df.head())

SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='? (<ipython-input-4-008e8524371a>, line 4)